# DO NOT CHANGE -> WILL BREAK copier LOGIC
_commit: v0.9.2
_src_path: https://github.com/taranis-ai/bot_template
author_mail: benjamin.akhras@ait.ac.at
description: Story Clustering Bot for Taranis AI
init_git_repo: false
models: louvain
project_name: story_clustering
repo_url: https://github.com/taranis-ai/story-clustering
